EN_EX_DIR=en/ex
INT_EN_EX_DIR=int/ex

include $(EN_EX_DIR)/m2-01/Makefile.def
include $(EN_EX_DIR)/m2-02/Makefile.def
include $(EN_EX_DIR)/m3-01/Makefile.def
include $(EN_EX_DIR)/m3-02/Makefile.def
include $(EN_EX_DIR)/m4-01/Makefile.def
include $(EN_EX_DIR)/m4-02/Makefile.def
include $(EN_EX_DIR)/m5-01/Makefile.def
