EN_EX_DIR=en/ex

include $(EN_EX_DIR)/m2-01/Makefile.def
include $(EN_EX_DIR)/m2-02/Makefile.def
include $(EN_EX_DIR)/m3-01/Makefile.def
include $(EN_EX_DIR)/m3-02/Makefile.def
include $(EN_EX_DIR)/m4-01/Makefile.def
