$(FINAL_EN_M6_01_CPPINTRO_LECT_PDF): $(EN_M6_01_CPPINTRO_PARTS) $(EN_CONFIG_INPUT)
	$(LATEXMK) -jobname=$(subst /,-,$(<D))-lect $(EN_M6_01_CPPINTRO_DIR)/slides-lect

$(FINAL_EN_M6_01_CPPINTRO_HOUT_PDF): $(EN_M6_01_CPPINTRO_PARTS) $(EN_CONFIG_INPUT)
	$(LATEXMK) -jobname=$(subst /,-,$(<D))-hout $(EN_M6_01_CPPINTRO_DIR)/slides-hout
