ES_LABS_DIR=es/labs

include $(ES_LABS_DIR)/01-cppdev/Makefile.def
include $(ES_LABS_DIR)/02-perfener/Makefile.def
include $(ES_LABS_DIR)/03-cache/Makefile.def
include $(ES_LABS_DIR)/05-ilp/Makefile.def
include $(ES_LABS_DIR)/05-omp/Makefile.def
include $(ES_LABS_DIR)/06-atomics/Makefile.def
