ES_LABS_DIR=es/labs

include $(ES_LABS_DIR)/lab1-cppdev/Makefile.def
include $(ES_LABS_DIR)/lab2-perfener/Makefile.def
include $(ES_LABS_DIR)/03-cache/Makefile.def
include $(ES_LABS_DIR)/05-ilp/Makefile.def
